### ISSUE TITLE
Mamba推理

### ISSUE THREAD

**Issue by shidn** [wangtz19/NetMamba#12]
针对Mamba本身的问题
请问下Mamba推理的时候，在decoder阶段需要将前面所有的token都输入吗？
Transformer里面，因为有KVCache所以减少了很多的计算量，Mamba是怎么处理的？

**Comment by wangtz19** [comment]
decoder只是pre-train阶段使用，用到全部输入token
kv cache需要多步生成才用到，即使NetMamba底层架构换成突然也仅需要单步decoder生成，不需要使用kv cache

**Comment by shidn** [comment]
那么这种单步推理场景下，推理速度相比Bert的优势就是因为模型变小带来的？

**Comment by wangtz19** [comment]
模型参数量小 + Mamba线性复杂度

**Comment by shidn** [comment]
Transformer的单步推理，复杂度也是O(n)的，序列推理的时候才是O(n2)吧。
