### ISSUE TITLE
About Dataset Usage in NetMamba

### ISSUE THREAD

**Issue by xxrelax** [wangtz19/NetMamba#13]
Hello,

I have been exploring your work on NetMamba and found it very impressive. I noticed that while you have included ET-bert in the comparison models, the CSTNET-TLS 1.3 dataset, which ET-bert has been tested on, is not used in your experiments.

Could you please share the reason for not using the CSTNET-TLS 1.3 dataset in your work? Understanding your rationale would be very helpful for my research.

Thank you for your time and for sharing this excellent work with the community!

**Comment by wangtz19** [comment]
Thank you for your interest in NetMamba! As you can see, there is a vast amount of public traffic data, making it challenging to cover all of them. We aim to encompass as many types as possible and categorize them into three tasks: encrypted application classification, attack traffic classification, and malware traffic classification.

Notably, the CSTNET-TLS 1.3 dataset falls under encrypted application classification, utilizing the TLS-based encryption technique. This technique is also employed in the CrossPlatform, ISCXTor2016, and ISCXVPN2016 datasets, which are used by NetMamba.
