### ISSUE TITLE
finetune过程报错AttributeError: 'NetMamba' object has no attribute 'decoder_pos_embed'

### ISSUE THREAD

**Issue by axh2018** [wangtz19/NetMamba#2]
按照readme来的，cuda版本12.1 gpu2080ti，pretrain完成了，finetune过程报错，请问一下是包没装好吗，谢谢

(NetMamba) root@autodl-container-b9b842b3fc-38b33995:~/autodl-tmp/NetMamba# CUDA_VISIBLE_DEVICES=0   python src/fine-tune.py     --blr 2e-3     --epochs 120     --nb_classes 7     --finetune   output/pretrain/checkpoint-step10000.pth     --data_path  dataset/ISCXVPN2016       --model  net_mamba_classifier     --no_amp
Not using distributed mode
[10:24:46.114657] job dir: /root/autodl-tmp/NetMamba/src
[10:24:46.114849] Namespace(batch_size=64,
epochs=120,
save_steps_freq=5000,
accum_iter=1,
model='net_mamba_classifier',
input_size=40,
drop_path=0.1,
clip_grad=None,
weight_decay=0.05,
lr=None,
blr=0.002,
layer_decay=0.75,
min_lr=1e-06,
warmup_epochs=20,
color_jitter=None,
aa='rand-m9-mstd0.5-inc1',
smoothing=0.1,
reprob=0.25,
remode='pixel',
recount=1,
resplit=False,
mixup=0,
cutmix=0,
cutmix_minmax=None,
mixup_prob=1.0,
mixup_switch_prob=0.5,
mixup_mode='batch',
finetune='output/pretrain/checkpoint-step10000.pth',
data_path='dataset/ISCXVPN2016',
nb_classes=7,
output_dir='./output/finetune',
log_dir='./output/finetune',
device='cuda',
seed=0,
resume='',
start_epoch=0,
eval=False,
dist_eval=False,
num_workers=10,
pin_mem=True,
world_size=1,
local_rank=-1,
dist_on_itp=False,
dist_url='env://',
if_amp=False,
distributed=False)
[10:24:46.161752] Dataset ImageFolder
    Number of datapoints: 13281
    Root location: dataset/ISCXVPN2016/train
    StandardTransform
Transform: Compose(
               Grayscale(num_output_channels=1)
               ToTensor()
               Normalize(mean=[0.5], std=[0.5])
           )
[10:24:46.166717] Dataset ImageFolder
    Number of datapoints: 1383
    Root location: dataset/ISCXVPN2016/valid
    StandardTransform
Transform: Compose(
               Grayscale(num_output_channels=1)
               ToTensor()
               Normalize(mean=[0.5], std=[0.5])
           )
[10:24:46.171635] Dataset ImageFolder
    Number of datapoints: 1384
    Root location: dataset/ISCXVPN2016/test
    StandardTransform
Transform: Compose(
               Grayscale(num_output_channels=1)
               ToTensor()
               Normalize(mean=[0.5], std=[0.5])
           )
[10:24:46.171723] Sampler_train = <torch.utils.data.distributed.DistributedSampler object at 0x7fc93b98fa00>
Traceback (most recent call last):
  File "/root/autodl-tmp/NetMamba/src/fine-tune.py", line 397, in <module>
    main(args)
  File "/root/autodl-tmp/NetMamba/src/fine-tune.py", line 234, in main
    model = models_net_mamba.__dict__[args.model](
  File "/root/autodl-tmp/NetMamba/src/models_net_mamba.py", line 275, in net_mamba_classifier
    model = NetMamba(
  File "/root/autodl-tmp/NetMamba/src/models_net_mamba.py", line 91, in __init__
    self.initialize_weights()
  File "/root/autodl-tmp/NetMamba/src/models_net_mamba.py", line 96, in initialize_weights
    trunc_normal_(self.decoder_pos_embed, std=.02)
  File "/root/miniconda3/envs/NetMamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'NetMamba' object has no attribute 'decoder_pos_embed'
(NetMamba) root@autodl-container-b9b842b3fc-38b33995:~/autodl-tmp/NetMamba# pip list
Package                  Version              Editable project location
------------------------ -------------------- -------------------------------------
absl-py                  2.1.0
addict                   2.4.0
aiohttp                  3.9.1
aiosignal                1.3.1
alembic                  1.13.0
asttokens                2.4.1
async-timeout            4.0.3
attrs                    23.1.0
Automat                  22.10.0
blinker                  1.7.0
buildtools               1.0.6
causal-conv1d            1.1.0
certifi                  2023.11.17
charset-normalizer       3.3.2
click                    8.1.7
cloudpickle              3.0.0
comm                     0.2.2
constantly               23.10.4
contourpy                1.2.0
cycler                   0.12.1
databricks-cli           0.18.0
datasets                 2.15.0
debugpy                  1.8.1
decorator                5.1.1
dill                     0.3.7
docker                   6.1.3
docopt                   0.6.2
einops                   0.7.0
entrypoints              0.4
exceptiongroup           1.2.0
executing                2.0.1
filelock                 3.13.1
Flask                    3.0.0
fonttools                4.46.0
frozenlist               1.4.0
fsspec                   2023.10.0
furl                     2.1.3
fvcore                   0.1.5.post20221221
gitdb                    4.0.11
GitPython                3.1.40
greenlet                 3.0.2
grpcio                   1.62.1
gunicorn                 21.2.0
huggingface-hub          0.19.4
hyperlink                21.0.0
idna                     3.6
importlib-metadata       7.0.0
incremental              22.10.0
iopath                   0.1.10
ipykernel                6.29.4
ipython                  8.22.2
itsdangerous             2.1.2
jedi                     0.19.1
Jinja2                   3.1.2
joblib                   1.3.2
jupyter_client           8.6.1
jupyter_core             5.7.2
kiwisolver               1.4.5
Mako                     1.3.0
mamba_ssm                1.1.1                /root/autodl-tmp/NetMamba/mamba-1p1p1
Markdown                 3.5.1
MarkupSafe               2.1.3
matplotlib               3.8.2
matplotlib-inline        0.1.6
mlflow                   2.9.1
mmcv                     1.3.8
mmsegmentation           0.14.1
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.15
nest-asyncio             1.6.0
networkx                 3.2.1
ninja                    1.11.1.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.4.99
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.2
opencv-python            4.8.1.78
orderedmultidict         1.0.1
packaging                23.2
pandas                   2.1.3
parso                    0.8.3
pexpect                  4.9.0
Pillow                   10.1.0
pip                      24.0
platformdirs             4.1.0
portalocker              2.8.2
prettytable              3.9.0
prompt-toolkit           3.0.43
protobuf                 4.25.1
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
pyarrow                  14.0.1
pyarrow-hotfix           0.6
Pygments                 2.17.2
PyJWT                    2.8.0
pyparsing                3.1.1
python-dateutil          2.8.2
python-hostlist          1.23.0
pytz                     2023.3.post1
PyYAML                   6.0.1
pyzmq                    25.1.2
querystring-parser       1.2.4
redo                     2.0.4
regex                    2023.10.3
requests                 2.31.0
safetensors              0.4.1
scapy                    2.5.0
scikit-learn             1.3.2
scipy                    1.11.4
setuptools               69.5.1
simplejson               3.19.2
six                      1.16.0
smmap                    5.0.1
SQLAlchemy               2.0.23
sqlparse                 0.4.4
stack-data               0.6.3
sympy                    1.12
tabulate                 0.9.0
tensorboard              2.16.2
tensorboard-data-server  0.7.2
termcolor                2.4.0
thop                     0.1.1.post2209072238
threadpoolctl            3.2.0
timm                     0.4.12
tokenizers               0.15.0
tomli                    2.0.1
torch                    2.1.1+cu121
torchaudio               2.1.1
torchprofile             0.0.4
torchvision              0.16.1+cu121
tornado                  6.4
tqdm                     4.66.1
traitlets                5.14.2
transformers             4.35.2
triton                   2.1.0
Twisted                  24.3.0
typing_extensions        4.8.0
tzdata                   2023.3
urllib3                  2.1.0
wcwidth                  0.2.12
websocket-client         1.7.0
Werkzeug                 3.0.1
wheel                    0.43.0
xxhash                   3.4.1
yacs                     0.1.8
yapf                     0.40.2
yarl                     1.9.4
zipp                     3.17.0
zope.interface           6.2

**Comment by wangtz19** [comment]
开源代码经过优化和精简，finetune未完全测试，现已修复并验证，请拉取最新版本代码
