### ISSUE TITLE
请问报文切分用的什么工具？

### ISSUE THREAD

**Issue by shidn** [wangtz19/NetMamba#3]
splitter = "/root/ShieldGPT/pcap_tool/splitter"

**Comment by wangtz19** [comment]
这是[Neptune](https://github.com/Neptune17)基于C++实现的pcap读写工具，本项目进行少量修改实现单向流切分，参见[ShieldGPT/pcap_tool](https://github.com/wangtz19/ShieldGPT/tree/master/pcap_tool)
