### ISSUE TITLE
数据集处理的时候，if_augment的选择依据是什么

### ISSUE THREAD

**Issue by shidn** [wangtz19/NetMamba#6]

**Comment by wangtz19** [comment]
流数量少的情况下可以通过采样增加样本量，流数量足够就不需要了

**Comment by shidn** [comment]
但是在下游任务中用这个if_augment，感觉不是很准确

比如文件下载，中间部分的报文是完全没有特征的

**Comment by wangtz19** [comment]
文件传输中间报文是满载荷，本身就是一类特征，并且增强的样本类型包含多类应用
