### ISSUE TITLE
使用python dataset_x.py分割pcap文件失败

### ISSUE THREAD

**Issue by hzy32123** [wangtz19/NetMamba#7]
您好，我在使用`python dataset_x.py`处理数据集时无法正确地分割出流量。

我先是在linux服务器上执行`python dataset_iscx_tor2016.py`，所有log日志都报错 _“pcap_tool/splitter: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory”_。在网上找到的解决方法因权限不够无法使用。

随后我在本地windows系统中执行`python dataset_iscx_tor2016.py`，系统中所有.log日志中都报错 _“'F:/traffic' 不是内部或外部命令，也不是可运行的程序或批处理文件。”_。

请问这种情况应该如何解决？

如下图，执行`python dataset_iscx_tor2016.py`后得到“flows”文件夹，但是里面的各个流量类别的文件夹都是空的，且log文件都报错 _“'F:/traffic' 不是内部或外部命令，也不是可运行的程序或批处理文件。”_
![Snipaste_2024-06-13_22-05-42](https://github.com/wangtz19/NetMamba/assets/157223023/5e3d6846-8b01-4515-b61a-44c998b0baf9)
![Snipaste_2024-06-13_22-14-09](https://github.com/wangtz19/NetMamba/assets/157223023/01bbf355-7e63-4c59-b468-b48294addd36)

**Comment by wangtz19** [comment]
目前pcap_tool/splitter仅编译了Linux可执行文件，可以考虑在WSL下运行
