### ISSUE TITLE
models_mamba.py中TypeError: Mamba.__init__() got an unexpected keyword argument 'init_layer_scale'

### ISSUE THREAD

**Issue by niebikong** [wangtz19/NetMamba#8]
def create_block(
    d_model,
    ssm_cfg=None,
    norm_epsilon=1e-5,
    drop_path=0.,
    rms_norm=False,
    residual_in_fp32=False,
    fused_add_norm=False,
    layer_idx=None,
    device=None,
    dtype=None,
    if_bimamba=False,
    bimamba_type="none",
    if_devide_out=False,
    init_layer_scale=None,
):
    if if_bimamba:
        bimamba_type = "v1"
    if ssm_cfg is None:
        ssm_cfg = {}
    factory_kwargs = {"device": device, "dtype": dtype}
    mixer_cls = partial(Mamba, layer_idx=layer_idx, bimamba_type=bimamba_type, if_devide_out=if_devide_out, init_layer_scale=init_layer_scale, **ssm_cfg, **factory_kwargs)
    
mixer_cls = partial(Mamba, layer_idx=layer_idx, bimamba_type=bimamba_type, if_devide_out=if_devide_out, init_layer_scale=init_layer_scale, **ssm_cfg, **factory_kwargs)在这句中，Mamba实例化没有bimamba_type，if_devide_out，init_layer_scale等参数

**Comment by wangtz19** [comment]
Mamba怎么安装的？

**Comment by niebikong** [comment]
https://github.com/state-spaces/mamba/releases/download/v1.1.3.post1/mamba_ssm-1.1.3.post1+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
我使用这个whl文件安装，代码修改成下面后也能执行mixer_cls = partial(Mamba, layer_idx=layer_idx, **ssm_cfg, **factory_kwargs)

**Comment by wangtz19** [comment]
应该版本迭代后接口变了，本项目使用1.1.1版本Mamba

**Comment by xxrelax** [comment]
Mamba1.1.1 也有这个问题

**Comment by cuteist** [comment]
> Mamba1.1.1 也有这个问题

根据[https://github.com/state-spaces/mamba/issues/315](https://github.com/state-spaces/mamba/issues/315)
看样子NetMamba用的是 vim 修改后的 Mamba，所以在 pip install 之后要执行：
```
cp -rf "mamba-1p1p1/mamba_ssm" "/envs/mamba/lib/python3.10/site-packages/" 
```
